### ISSUE TITLE
break condition on filter_bias loop

### ISSUE THREAD

**Issue by weihangzhang** [LemonNoel/ATransN#1]
Hi,

https://github.com/LemonNoel/ATransN/blob/2e6cefc28261bce0c1604dc873278b30de00b9a2/src/dataset.py#L149
https://github.com/LemonNoel/ATransN/blob/2e6cefc28261bce0c1604dc873278b30de00b9a2/src/dataset.py#L160
Please correct me if I am wrong: I am wondering should these two lines use "or" instead of "and" when you determine when to break the loop of setting filter_bias? Otherwise for a triple (h,r1,t), it would potentially assign negative filter_bias to triples like (h, r2, t), which is not expected.

**Comment by LemonNoel** [comment]
Thanks for your pointing out this bug. We have written a script ([compute_error_ratio.py.zip](https://github.com/LemonNoel/ATransN/files/8523449/compute_error_ratio.py.zip)) to identify the ratio of filter_bias being affected.

And the results are as listed in this file ([error_ratio_results.txt](https://github.com/LemonNoel/ATransN/files/8523477/error_ratio_results.txt)). Considering about 0.3% would be mistakenly regarded as positive pairs on average and all models shared the same errors, we can think the conclusion in our paper still holds. We will update our code. Thank you very much!

**Comment by weihangzhang** [comment]
Hi,

Thanks very much for the reply.
Definitely agree that although this would impact the result numbers, the comparisons of experimental results reported in the paper should still theoratically holds.
